module.exports = [
  {
    category: "Burger",
    name: "Cheeseburger",
    desc: "This is a cheeseburger",
    price: 7.99,
  },
  {
    category: "Burger",
    name: "Double Cheeseburger",
    desc: "This is a double cheeseburger",
    price: 9.99,
  },
  {
    category: "Pizza",
    name: "Cheese Pizza",
    desc: "This is a slice of cheese pizza",
    price: 1.99,
  },
  {
    category: "Pizza",
    name: "Pepperoni Pizza",
    image: "https://media.gettyimages.com/id/938742222/photo/cheesy-pepperoni-pizza.jpg?s=612x612&w=gi&k=20&c=xzn3CpUBUV5Sa1UFftWFoSz1W_mp6fEN1G4_bQlDxZU=",
    desc: "This is a slice of pepperoni pizza",
    price: 2.99,
  },
  {
    category: "Fries",
    name: "Bag of Fries",
    desc: "This is a regular bag of fries",
    price: 2.99,
  },
  {
    category: "Fries",
    name: "Large bag of Fries",
    desc: "This is a large bag of fries",
    price: 3.99,
  },
  {
    category: "Drinks",
    name: "805 Beer",
    desc: "A bottle of 805",
    price: 5.99,
  },
  {
    category: "Drinks",
    name: "Guinness",
    image: "https://media.gettyimages.com/id/458646129/photo/pint-of-guinness.jpg?s=612x612&w=gi&k=20&c=LzToGuPALN2ZS1woidXCrUV203ZOUGzzPsxjPjZNj0c=",
    desc: "A bottle of Guinness",
    price: 5.99,
  },
  {
    category: "Drinks",
    name: "Large Soda",
    desc: "A cup of large soda of choice",
    price: 2.99,
  },
  {
    category: "Dessert",
    name: "Chocolate Sundae",
    desc: "This is a chocoalte sundae",
    price: 5.99,
  },
  {
    category: "Dessert",
    name: "Strawberry Milkshake",
    desc: "This is a strawberry milkshake",
    price: 5.99,
  },
];
