module.exports = [
  {
    category: "burger",
    name: "Cheeseburger",
    image: "https://www.pinclipart.com/picdir/big/74-740439_png-free-library-cutie-mark-you-can-mlp.png",
    desc: "This is a cheeseburger",
    price: 7.99,
  },
  {
    category: "burger",
    name: "Double Cheeseburger",
    image: "https://www.pinclipart.com/picdir/big/561-5614873_burger-you-will-want-to-taste-after-you.png",
    desc: "This is a double cheeseburger",
    price: 9.99,
  },
  {
    category: "pizza",
    name: "Cheese Pizza",
    image: "https://www.pinclipart.com/picdir/big/544-5448856_pizza-clip-slice-cheese-pizza-slice-clip-art.png",
    desc: "This is a slice of cheese pizza",
    price: 1.99,
  },
  {
    category: "pizza",
    name: "Pepperoni Pizza",
    image: "https://www.pinclipart.com/picdir/big/565-5659618_pizza-slices-clipart-stickers-pizza-png-download.png",
    desc: "This is a slice of pepperoni pizza",
    price: 2.99,
  },
  {
    category: "fries",
    name: "Bag of Fries",
    image: "https://www.pinclipart.com/picdir/big/522-5223149_fries-clipart-potato-fry-fried-food-clipart-png.png",
    desc: "This is a regular bag of fries",
    price: 2.99,
  },
  {
    category: "fries",
    name: "Large bag of Fries",
    image: "https://www.pinclipart.com/picdir/big/522-5223149_fries-clipart-potato-fry-fried-food-clipart-png.png",
    desc: "This is a large bag of fries",
    price: 3.99,
  },
  {
    category: "drink",
    name: "805 Beer",
    image: "https://www.pinclipart.com/picdir/big/566-5669945_beer-draft-png-transparent-background-clipart.png",
    desc: "A bottle of 805",
    price: 5.99,
  },
  {
    category: "drink",
    name: "Guinness",
    image: "https://media.gettyimages.com/id/458646129/photo/pint-of-guinness.jpg?s=612x612&w=gi&k=20&c=LzToGuPALN2ZS1woidXCrUV203ZOUGzzPsxjPjZNj0c=",
    desc: "A bottle of Guinness",
    price: 5.99,
  },
  {
    category: "drink",
    name: "Large Soda",
    image: "https://www.pinclipart.com/picdir/big/567-5678424_symbol-drinks-cherry-soda-clipart-png-download.png",
    desc: "A cup of large soda of choice",
    price: 2.99,
  },
  {
    category: "dessert",
    name: "Sundae",
    image: "https://www.pinclipart.com/picdir/big/545-5457591_transparent-ice-cream-clipart-ice-cream-sundae-clipart.png",
    desc: "This is a chocoalte sundae",
    price: 5.99,
  },
  {
    category: "dessert",
    name: "Strawberry Milkshake",
    image: "https://www.pinclipart.com/picdir/big/521-5216975_strawberry-milkshake-png-clipart-milkshake-clipart-transparent-png.png",
    desc: "This is a strawberry milkshake",
    price: 5.99,
  },
];
